export const TabCards = [
    [
        {domain: '.com', price: '$5.99/yr', descrition: 'instead of $10.99/year', button:'Buy Now'},
        {domain: '.ai', price: '$5.99/yr', descrition: 'instead of $10.99/year', button:'Buy Now'},
        {domain: '.net', price: '$5.99/yr', descrition: 'instead of $10.99/year', button:'Buy Now'},
        {domain: '.HEALTH', price: '$55.99/yr', descrition: 'instead of $10.99/year', button:'Buy Now'},
        {domain: '.CO.UK', price: '$5.99/yr', descrition: 'instead of $10.99/year', button:'Buy Now'},
        {domain: '.ORG', price: '$59.99/yr', descrition: 'instead of $10.99/year', button:'Buy Now'},
        {domain: '.CO', price: '$56.99/yr', descrition: 'instead of $10.99/year', button:'Buy Now'},
        {domain: '.SEA', price: '$51.99/yr', descrition: 'instead of $10.99/year', button:'Buy Now'},
    ],
    [
        {domain: 'BlueHost', price: '£2.46/mo', descrition: 'Bluehost -Extremely fast & reliable hosting with plenty', button:'Visit Site'},
        {domain: 'Ionos', price: '£2.46/mo', descrition: 'IONOS -Fast and secure hosting to help your business grow', button:'Visit Site'},
        {domain: 'Hostinger', price: '£2.46/mo', descrition: 'Hostinger -Scalable hosting solutions for fast websites',button:'Visit Site'},
        {domain: 'HostGator', price: '£2.46/mo', descrition: 'HostGator -Easy and affordable web hosting with intuitive', button:'Visit Site'},
        {domain: 'DreamHost', price: '£2.46/mo', descrition: 'DreamHost -Flexible hosting solutions to ensure your success', button:'Visit Site'},
        {domain: 'A2 Hosting', price: '£2.46/mo', descrition: 'A2 Hosting -High-powered web hosting with plans to suit',button:'Visit Site'},
        {domain: 'GoDadddy', price: '£2.46/mo', descrition: 'GoDaddy -Complete hosting solutions for any website', button:'Visit Site'},
        {domain: 'Network Solutions', price: '£2.46/mo', descrition: 'Network Solutions -Cloud-based web hosting', button:'Visit Site'},
    ],
    [
        {domain: 'HostGator',  descrition: 'Best for Customer Support', button:'Check Price'},
        {domain: 'AccuWeb ', descrition: 'Best for Linux- or Windows-Based Servers', button:'Check Price'},
        {domain: 'Hostwinds', descrition: 'Best for Easily Customizable Packages',button:'Check Price'},
        {domain: 'HostInMotion', descrition: 'Best for Free IP Addresses', button:'Check Price'},
        {domain: 'Liquid ', descrition: 'Best for Enterprise-Level Dedicated Hosting', button:'Check Price'},
        {domain: 'TMDHosting', descrition: 'Best for Fully Managed Hosting',button:'Check Price'},
        {domain: 'GoDadddy', descrition: 'Best for Full Root Access', button:'Check Price'},
        {domain: 'DreamHost',descrition: 'Best for Unlimited Monthly Data Transfers', button:'Check Price'},
    ],
    [
        {domain: 'UpCloud',price: '£2.46/mo',  descrition: 'UpCloud Ltd provides software solutions. The Company offers infrastructure-as-a-service for the business critical customers through cloud servers. UpCloud serves customers worldwide.', button:'Watch More'},
        {domain: 'Alibaba Cloud ', price: '£2.46/mo', descrition: 'Alibaba Cloud, also known as Aliyun, is a cloud computing company, a subsidiary of Alibaba Group. Alibaba Cloud provides cloud computing services to online businesses and Alibabas', button:'Watch More'},
        {domain: 'Liquid Web', price: '£2.46/mo', descrition: 'Liquid Web, Inc. is a provider of web hosting services based in Lansing, Michigan, United States. They provide dedicated managed servers, VPS servers, Smart Servers, shared hosting',button:'Watch More'},
        {domain: 'InterServer', price: '£2.46/mo', descrition: 'Interserver product line to includes dedicated servers, colocation and managed services. In 2006, InterServer built a datacenter in Secaucus, New Jersey. InterServer with its exceptional', button:'Watch More'},
        {domain: 'Vultr ', price: '£2.46/mo', descrition: 'Vultr is an ultra-reliable cloud platform that is within close proximity to the world’s developers. We’ve perfected the art and science of cloud infrastructure with our wide array of cloud, bare', button:'Watch More'},
        {domain: 'InMotion', price: '£2.46/mo', descrition: 'InMotion Hosting is an industry-leading provider of Shared Hosting, WordPress Hosting, VPS Hosting, Dedicated Servers and Hosted Private Cloud. Our reliable systems and network are state,',button:'Watch More'},
        {domain: 'AWS', price: '£2.46/mo', descrition: 'Amazon Web Services, Inc. is a subsidiary of Amazon that provides on-demand cloud computing platforms and APIs to individuals, companies, and governments, on a metered, pay-as-you-go basis.', button:'Watch More'},
        {domain: 'ServerSpace',price: '£2.46/mo', descrition: 'ServerSpace Ltd. provides IT managed services. The Company offers cloud hosting, hosted exchange, dedicated servers, application hosting, SaaS hosting, and connectivity solutions.', button:'Watch More'},
    ],
    [
        {domain: 'Hostwinds', price: 'Introductory Offer $2.64/mo', descrition: 'Bluehost -Extremely fast & reliable hosting with plenty', button:'Visit Site'},
        {domain: 'AccuWeb ', price: 'Introductory Offer $2.64/mo', descrition: 'IONOS -Fast and secure hosting to help your business grow', button:'Visit Site'},
        {domain: 'Liquid ', price: ' Introductory Offer £2.46/mo', descrition: 'Hostinger -Scalable hosting solutions for fast websites',button:'Visit Site'},
        {domain: 'WP Engine ', price: ' Introductory Offer £2.46/mo', descrition: 'HostGator -Easy and affordable web hosting with intuitive', button:'Visit Site'},
        {domain: 'FatCow', price: 'Introductory Offer £2.46/mo', descrition: 'DreamHost -Flexible hosting solutions to ensure your success', button:'Visit Site'},
        {domain: 'A2 Hosting', price: 'Introductory Offer 2.46/mo', descrition: 'A2 Hosting -High-powered web hosting with plans to suit',button:'Visit Site'},
        {domain: 'GoDadddy', price: 'Introductory Offer £2.46/mo', descrition: 'GoDaddy -Complete hosting solutions for any website', button:'Visit Site'},
        {domain: 'HostGator', price: 'Introductory Offer £2.46/mo', descrition: 'Network Solutions -Cloud-based web hosting with easy', button:'Visit Site'},
    ],
    [
        {domain: 'SiteGround', price: '$1.99 per mailbox per month ', descrition: 'Unlimited Not applicable', button:'Visit Site'},
        {domain: 'Zoho Mail  ', price: ' $1.99 per mailbox per month ', descrition: '5 GB to unlimited	250 MB to 1 GB',button:'Visit Site'},
        {domain: 'A2 Hosting ', price: ' $1.99 per mailbox per month ', descrition: '30 GB to 5 TB	25 MB', button:'Visit Site'},
        {domain: 'Google Workspace ', price: ' $1.99 per mailbox per month ', descrition: 'DreamH30 GB to 5 TB	25 MB', button:'Visit Site'},
        {domain: 'A2 Hosting', price: '$1.99 per mailbox per month ', descrition: '25 GB-Not applicable',button:'Visit Site'},
        {domain: 'GoDadddy', price: '$1.99 per mailbox per month ', descrition: 'Unlimited Not applicable', button:'Visit Site'},
        {domain: 'HostGator', price: ' $1.99 per mailbox per month ', descrition: 'Unlimited Not applicable', button:'Visit Site'},
        {domain: 'DreamHost', price: '$1.99 per mailbox per month ', descrition: '25 GB	Not applicable', button:'Visit Site'},
    ],
    [
        {domain: 'Hostwinds ', price: '$1.99 per mailbox per month ', descrition: '.Hostwinds offers excellent VPS packages, earning it our Editors’ Choice award for the category. ', button:'Visit Site'},
        {domain: 'InMotion  ', price: ' $1.99 per mailbox per month ', descrition: 'InMotion has a dense feature-set and reasonable pricing for its shared, dedicated, reseller',button:'Visit Site'},
        {domain: 'Hostinger  ', price: ' $1.99 per mailbox per month ', descrition: 'Hostinger’s VPS plans are all self-managed, meaning you must configure and manage your server', button:'Visit Site'},
        {domain: 'Liquid ', price: ' $1.99 per mailbox per month ', descrition: 'iquid Web has a fantastic selection of cloud, dedicated, WordPress, and VPS packages, though these', button:'Visit Site'},
        {domain: 'AccuWeb', price: '$1.99 per mailbox per month ', descrition: '25 GB-NThe companys VPS plans are particularly stacked, and they come with unlimited email accounts',button:'Visit Site'},
        {domain: 'GoDadddy', price: '$1.99 per mailbox per month ', descrition: 'GoDaddy is one of the most recognizable domain sellers around, and provides dependable web hosting', button:'Visit Site'},
        {domain: 'HostGator', price: ' $1.99 per mailbox per month ', descrition: 'HostGator’s excellent shared hosting earned the company a PCMag Editors’ Choice award, but don’t' , button:'Visit Site'},
        {domain: 'DreamHost', price: '$1.99 per mailbox per month ', descrition: 'InMotion has a dense feature-set and reasonable pricing for its shared, dedicated, reseller, and', button:'Visit Site'},
    ],
    [
    {domain: 'Hostinger', descrition: 'Best free website hosting overall', button:'Visit Site'},
    {domain: 'Infinityfree ', descrition: 'Best for Windows-Based Servers', button:'Visit Site'},
    {domain: 'Byethost', descrition: 'Best for Easily Customizable',button:'Visit Site'},
    {domain: ' 000Webhost', descrition: 'Best for Free IP Addresses', button:'Visit Site'},
    {domain: 'Googiehost ', descrition: 'Best for Enterprise-Level Dedicated', button:'Visit Site'},
    {domain: ' FreeHostingNoAds', descrition: 'Best for Fully Managed Hosting',button:'Visit Site'},
    {domain: 'FreeWebHostingArea', descrition: 'Best for Full Root Access', button:'Visit Site'},
    {domain: 'DreamHost',descrition: 'Best for Unlimited  Data Transfers', button:'Visit Site'},
    ]
]

